plugins {
    id('com.android.library')
}

android {
    namespace 'com.pengxh.kt.lite'
    compileSdk 37

    lint {
        disable 'NewerVersionAvailable'
        disable 'GradleDependency'
    }

    defaultConfig {
        minSdk 26
        consumerProguardFiles('consumer-rules.pro')
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    buildFeatures {
        buildConfig true
        viewBinding true
    }

    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
        }
    }
}

dependencies {
    // 基础 AndroidX
    implementation 'androidx.core:core-ktx:1.18.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'

    // 网络相关（统一为最新稳定版）
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation 'com.squareup.retrofit2:converter-scalars:3.0.0'
    implementation 'com.squareup.okhttp3:okhttp:5.4.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:5.4.0'

    //图片加载
    implementation 'com.github.bumptech.glide:glide:4.16.0'

    //官方Json解析库
    implementation 'com.google.code.gson:gson:2.14.0'

    // Kotlin 协程/MVVM
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.11.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.11.0'

    //Socket (TcpClient 基于 Netty)
    implementation 'io.netty:netty-all:4.1.115.Final'
}